"""Initial schema for the AreaScan tourism platform.

Hand-written (not autogenerated): there is no database available at authoring
time, so this migration bootstraps a fresh Cloud SQL ``travel_app`` database
from scratch — required PostgreSQL extensions, all 18 tables (incl. join
tables) in FK-dependency order, and every index from docs/DATABASE.md.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-17
"""

from __future__ import annotations

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ===== Extensions (bootstrap a fresh database) =====
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")  # fuzzy/text search
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")  # case-insensitive email
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")  # gen_random_uuid()

    # ===== RBAC =====
    op.create_table(
        "roles",
        sa.Column("id", sa.SmallInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )

    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("google_sub", sa.Text(), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "email_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_users_google_sub")),
    )

    op.create_table(
        "user_roles",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_roles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_user_roles_role_id_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )

    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_refresh_tokens"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index("ix_refresh_user", "refresh_tokens", ["user_id"])

    # ===== Geography lookup =====
    op.create_table(
        "provinces",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=True),
        sa.Column("name_th", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=True),
        sa.Column(
            "centroid",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False
            ),
            nullable=True,
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geography(
                geometry_type="MULTIPOLYGON", srid=4326, spatial_index=False
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provinces")),
        sa.UniqueConstraint("code", name=op.f("uq_provinces_code")),
    )

    op.create_table(
        "districts",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=True),
        sa.Column("name_th", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=True),
        sa.Column(
            "centroid",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False
            ),
            nullable=True,
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geography(
                geometry_type="MULTIPOLYGON", srid=4326, spatial_index=False
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["province_id"],
            ["provinces.id"],
            name=op.f("fk_districts_province_id_provinces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_districts")),
    )
    op.create_index("ix_districts_province", "districts", ["province_id"])

    op.create_table(
        "place_categories",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name_th", sa.String(length=120), nullable=False),
        sa.Column("name_en", sa.String(length=120), nullable=True),
        sa.Column("icon", sa.String(length=40), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place_categories")),
        sa.UniqueConstraint("code", name=op.f("uq_place_categories_code")),
    )

    # ===== Core POI =====
    op.create_table(
        "places",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "kind",
            sa.String(length=20),
            server_default=sa.text("'attraction'"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT", srid=4326, spatial_index=False
            ),
            nullable=False,
        ),
        sa.Column(
            "rating_avg",
            sa.Numeric(precision=2, scale=1),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "rating_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("price_level", sa.SmallInteger(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("opening_hours", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_level BETWEEN 1 AND 4", name=op.f("ck_places_price_level_range")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["place_categories.id"],
            name=op.f("fk_places_category_id_place_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["province_id"],
            ["provinces.id"],
            name=op.f("fk_places_province_id_provinces"),
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
            name=op.f("fk_places_district_id_districts"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_places_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
        sa.UniqueConstraint("slug", name=op.f("uq_places_slug")),
    )
    # Spatial GIST index on the geography column.
    op.create_index(
        "ix_places_location", "places", ["location"], postgresql_using="gist"
    )
    # GIN trigram index for fuzzy name search.
    op.create_index(
        "ix_places_name_trgm",
        "places",
        ["name"],
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index("ix_places_category", "places", ["category_id"])
    op.create_index("ix_places_status", "places", ["status"])
    op.create_index("ix_places_kind", "places", ["kind"])

    op.create_table(
        "restaurants",
        sa.Column("place_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("cuisine", postgresql.ARRAY(sa.String(length=80)), nullable=True),
        sa.Column("price_range", sa.String(length=20), nullable=True),
        sa.Column(
            "has_delivery", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column("menu_url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_restaurants_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("place_id", name=op.f("pk_restaurants")),
    )

    op.create_table(
        "shops",
        sa.Column("place_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("shop_type", sa.String(length=40), nullable=True),
        sa.Column("products", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_shops_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("place_id", name=op.f("pk_shops")),
    )

    op.create_table(
        "activities",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("place_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("category", sa.String(length=60), nullable=True),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_activities_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )

    # ===== Tags / Images =====
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("slug", name=op.f("uq_tags_slug")),
    )

    op.create_table(
        "place_tags",
        sa.Column("place_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_place_tags_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("fk_place_tags_tag_id_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("place_id", "tag_id", name=op.f("pk_place_tags")),
    )

    op.create_table(
        "images",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("owner_type", sa.String(length=20), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("alt", sa.String(length=200), nullable=True),
        sa.Column(
            "is_cover", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
    )
    op.create_index("ix_images_owner", "images", ["owner_type", "owner_id"])

    # ===== Reviews / Favorites =====
    op.create_table(
        "reviews",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("place_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name=op.f("ck_reviews_rating_range")),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_reviews_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_reviews_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("place_id", "user_id", name="uq_reviews_place_user"),
    )
    op.create_index("ix_reviews_place", "reviews", ["place_id"])

    op.create_table(
        "favorites",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("place_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_favorites_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_favorites_place_id_places"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "place_id", name=op.f("pk_favorites")),
    )

    # ===== Trips =====
    op.create_table(
        "trips",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("days", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("budget", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_ai", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ai_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("days BETWEEN 1 AND 30", name=op.f("ck_trips_days_range")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_trips_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["province_id"],
            ["provinces.id"],
            name=op.f("fk_trips_province_id_provinces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    )
    op.create_index("ix_trips_user", "trips", ["user_id"])

    op.create_table(
        "trip_items",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("trip_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("place_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("day_no", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("est_cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
            name=op.f("fk_trip_items_trip_id_trips"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name=op.f("fk_trip_items_place_id_places"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_items")),
    )
    op.create_index(
        "ix_trip_items_trip", "trip_items", ["trip_id", "day_no", "sort_order"]
    )


def downgrade() -> None:
    # Drop tables in reverse FK-dependency order.
    op.drop_index("ix_trip_items_trip", table_name="trip_items")
    op.drop_table("trip_items")
    op.drop_index("ix_trips_user", table_name="trips")
    op.drop_table("trips")
    op.drop_table("favorites")
    op.drop_index("ix_reviews_place", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_images_owner", table_name="images")
    op.drop_table("images")
    op.drop_table("place_tags")
    op.drop_table("tags")
    op.drop_table("activities")
    op.drop_table("shops")
    op.drop_table("restaurants")
    op.drop_index("ix_places_kind", table_name="places")
    op.drop_index("ix_places_status", table_name="places")
    op.drop_index("ix_places_category", table_name="places")
    op.drop_index("ix_places_name_trgm", table_name="places")
    op.drop_index("ix_places_location", table_name="places")
    op.drop_table("places")
    op.drop_table("place_categories")
    op.drop_index("ix_districts_province", table_name="districts")
    op.drop_table("districts")
    op.drop_table("provinces")
    op.drop_index("ix_refresh_user", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("user_roles")
    op.drop_table("users")
    op.drop_table("roles")

    # NOTE: extensions (postgis, pg_trgm, citext, pgcrypto) are intentionally
    # left installed. Dropping them is unsafe if other databases/objects depend
    # on them, and they are harmless to leave in place on a downgrade.
